### ISSUE TITLE
Throws without arguments

### ISSUE THREAD

**Issue by raine** [domtronn/ramda-suggest#1]
```
% ramda-suggest                                                                                                                                      
/Users/raine/.nvm/versions/node/v8.1.1/lib/node_modules/ramda-suggest/bin/ramda-suggest.js:21
if (/\(.*?\) => .*/.test(output.toString())) {
                               ^

TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/Users/raine/.nvm/versions/node/v8.1.1/lib/node_modules/ramda-suggest/bin/ramda-suggest.js:21:32)
    at Module._compile (module.js:569:30)
```

**Comment by domtronn** [comment]
Thanks for the find! :)

Hopefully that should be fixed now... Problems with both casting `undefined` to a string and default usage if not enough arguments given
